name: check

on: push

jobs:
  check:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['8.0', '7.4']

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - run: git fetch origin master

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phplint 7.4
      uses: StephaneBour/actions-php-lint@7.4
      if: ${{ matrix.php }} == '7.4'

    - name: Run phplint 8.0
      uses: StephaneBour/actions-php-lint@8.0
      if: ${{ matrix.php }} == '8.0'

    - name: Show changed files
      run: composer changed-files

    - name: Run phpdoccheck
      run: composer phpdoccheck-diff

    - name: Run phpcs
      run: composer phpcs-diff

    - name: Run phpunit
      run: composer phpunit
